### ISSUE TITLE
Cannot enable opencl renderer in Fractorium if two GPUs are present

### ISSUE THREAD

**Issue by gh2k** [gh2k/fractorium#7]
This is the same issue as fmeemster/fractorium#13 but I'm opening this here as I intend to look at it.

**Comment by mfeemster** [comment]
This should be fixed now. Please pull the latest and build to verify it works on Mac and Linux. Thanks.

**Comment by gh2k** [comment]
Unfortunately @mfeemster (and I'm really sorry about only just now getting round to testing this) I still have the same issue on my Linux box. I don't have access to a mac with two GPUs to test. I'll try and figure out why it fails, but the only output regarding the error is:

````
Init: failed to init all devices and platforms.

Error initializing OpenCL renderer, using CPU renderer instead.
````

**Comment by mfeemster** [comment]
What are your GPUs? I will begin troubleshooting this now as I realized I have never actually ran multi-gpu on Linux.

**Comment by gh2k** [comment]
Two AMD HD 7970s. They're wired up in crossfire but I don't have that enabled on Linux. I've yet to test the Windows build on my Win8 install, so that might shed some light on whether it's a Linux-specific issue.
